apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: eaxohd5zd-go 
  janus-idp.io/tekton: eaxohd5zd-go
  backstage.io/kubernetes-id: eaxohd5zd-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: eaxohd5zd-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml