apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: eaxohd5zd-go
  janus-idp.io/tekton: eaxohd5zd-go
  backstage.io/kubernetes-id: eaxohd5zd-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: eaxohd5zd-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
